name: CI Workflow

on:
  push:
    branches: [ main ]

  pull_request:

jobs:

  code-style:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Check code style
        run: yarn lint

  tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Check code style
        run: yarn test

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Get initial dist checksum
        id: initial-dist-checksum
        run: |
          if [ -d "dist" ]; then
            echo "checksum=$(find dist -type f -exec md5sum {} \; | sort -k 2 | md5sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          else
            echo "checksum=none" >> $GITHUB_OUTPUT
          fi

      - name: Get initial bin checksum
        id: initial-bin-checksum
        run: |
          if [ -d "bin" ]; then
            echo "checksum=$(find bin -type f -exec md5sum {} \; | sort -k 2 | md5sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          else
            echo "checksum=none" >> $GITHUB_OUTPUT
          fi

      - name: Get initial preview checksum
        id: initial-preview-checksum
        run: |
          if [ -d "preview" ]; then
            echo "checksum=$(find preview -type f -exec md5sum {} \; | sort -k 2 | md5sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          else
            echo "checksum=none" >> $GITHUB_OUTPUT
          fi

      - name: Build
        run: yarn build

      - name: Verify dist checksum
        run: |
          NEW_CHECKSUM=$(find dist -type f -exec md5sum {} \; | sort -k 2 | md5sum | cut -d' ' -f1)
          INITIAL_CHECKSUM=${{ steps.initial-dist-checksum.outputs.checksum }}
          
          if [ "$INITIAL_CHECKSUM" != "none" ] && [ "$NEW_CHECKSUM" != "$INITIAL_CHECKSUM" ]; then
            echo "Error: dist folder content changed after build"
            echo "Initial checksum: $INITIAL_CHECKSUM"
            echo "New checksum: $NEW_CHECKSUM"
            echo "Please run 'yarn build' locally and commit the changes."
            exit 1
          fi

      - name: Verify bin checksum
        run: |
          NEW_CHECKSUM=$(find bin -type f -exec md5sum {} \; | sort -k 2 | md5sum | cut -d' ' -f1)
          INITIAL_CHECKSUM=${{ steps.initial-bin-checksum.outputs.checksum }}
          
          if [ "$INITIAL_CHECKSUM" != "none" ] && [ "$NEW_CHECKSUM" != "$INITIAL_CHECKSUM" ]; then
            echo "Error: bin folder content changed after build"
            echo "Initial checksum: $INITIAL_CHECKSUM"
            echo "New checksum: $NEW_CHECKSUM"
            echo "Please run 'yarn build:cli' locally and commit the changes."
            exit 1
          fi

      - name: Verify preview checksum
        run: |
          NEW_CHECKSUM=$(find preview -type f -exec md5sum {} \; | sort -k 2 | md5sum | cut -d' ' -f1)
          INITIAL_CHECKSUM=${{ steps.initial-preview-checksum.outputs.checksum }}
          
          if [ "$INITIAL_CHECKSUM" != "none" ] && [ "$NEW_CHECKSUM" != "$INITIAL_CHECKSUM" ]; then
            echo "Error: preview folder content changed after build"
            echo "Initial checksum: $INITIAL_CHECKSUM"
            echo "New checksum: $NEW_CHECKSUM"
            echo "Please run 'yarn build:preview' locally and commit the changes."
            exit 1
          fi
